# Generated by Django 5.2.7 on 2025-10-09 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ACCOUNT_ALERT', 'Account Alert'), ('SYSTEM_MESSAGE', 'System Message'), ('ASSIGNMENT_DUE', 'Assignment Due'), ('ASSIGNMENT_GRADED', 'Assignment Graded'), ('NEW_POST', 'New Classroom Post'), ('RESOURCE_APPROVED', 'Resource Approved'), ('POST_REPLY', 'Post Reply'), ('COMMENT_REPLY', 'Comment Reply'), ('NEW_FOLLOWER', 'New Follower'), ('MENTION', 'Mention'), ('NEW_MESSAGE', 'New Message'), ('CRISIS_ALERT', 'Crisis Alert'), ('TICKET_RESPONSE', 'Support Ticket Response')], max_length=30)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx')],
            },
        ),
    ]
