# Generated by Django 5.2.7 on 2025-10-09 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('engagement', 'Engagement'), ('academic', 'Academic'), ('wellbeing', 'Wellbeing'), ('operational', 'Operational'), ('social', 'Social'), ('transport', 'Transport')], max_length=20)),
                ('description', models.TextField()),
                ('calculation_query', models.TextField(blank=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('dropout_risk', 'Dropout Risk'), ('performance', 'Performance Prediction'), ('engagement', 'Engagement Trend'), ('wellbeing', 'Wellbeing Risk')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('average_engagement', models.FloatField(default=0)),
                ('assignment_completion_rate', models.FloatField(default=0)),
                ('average_grade', models.FloatField(default=0)),
                ('post_activity', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_value', models.FloatField()),
                ('confidence', models.FloatField()),
                ('factors', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.predictivemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('average_engagement', models.FloatField(default=0)),
                ('wellbeing_index', models.FloatField(default=0)),
                ('transport_punctuality', models.FloatField(default=0)),
                ('social_activity', models.IntegerField(default=0)),
                ('financial_health', models.FloatField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('login_count', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('assignments_completed', models.IntegerField(default=0)),
                ('average_grade', models.FloatField(blank=True, null=True)),
                ('attendance_rate', models.FloatField(default=0)),
                ('resources_accessed', models.IntegerField(default=0)),
                ('study_time_minutes', models.IntegerField(default=0)),
                ('posts_created', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('mood_average', models.FloatField(blank=True, null=True)),
                ('wellbeing_posts', models.IntegerField(default=0)),
                ('transport_attendance', models.FloatField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
