# Generated by Django 5.2.7 on 2025-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ai_clarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ai_difficulty_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='classpost',
            name='toxicity_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='comment',
            name='toxicity_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
