# Generated by Django 5.2.7 on 2025-10-09 09:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(help_text='XP cost to redeem this item.', validators=[django.core.validators.MinValueValidator(0)])),
                ('item_type', models.CharField(choices=[('VIRTUAL', 'Virtual Badge/Item'), ('DISCOUNT', 'Discount/Coupon'), ('TANGIBLE', 'Tangible Prize'), ('PRIVILEGE', 'Privilege/Exemption')], default='VIRTUAL', max_length=20)),
                ('stock', models.IntegerField(default=-1, help_text='Number of items available. -1 means unlimited.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemable_items', to='users.school')),
            ],
            options={
                'db_table': 'redeemable_items',
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Fulfillment'), ('FULFILLED', 'Fulfilled'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('fulfillment_details', models.TextField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rewards.redeemableitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_transactions',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
