# Generated by Django 5.2.7 on 2025-10-09 09:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('NLP', 'Natural Language Processing'), ('TOXICITY', 'Toxicity/Safety Filter'), ('RECOMMENDATION', 'Recommendation Engine'), ('SUMMARIZATION', 'Summarization'), ('QNA', 'Question Answering')], max_length=20)),
                ('provider', models.CharField(default='Google Gemini/OpenAI', max_length=50)),
                ('api_key_env', models.CharField(help_text='Environment variable name for the API Key.', max_length=50)),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_tokens', models.IntegerField(default=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Configuration',
                'db_table': 'ai_model_configs',
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_app', models.CharField(choices=[('ELIBRARY', 'eLibrary'), ('SOCIAL', 'Social'), ('WELLBEING', 'Wellbeing'), ('ANALYTICS', 'Analytics')], default='ELIBRARY', max_length=20)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('latency_ms', models.IntegerField(default=0, help_text='Latency in milliseconds.')),
                ('was_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodelconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request Log',
                'db_table': 'ai_request_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
