# Generated by Django 5.2.7 on 2025-10-09 09:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('LINK', 'External Link'), ('PRESENTATION', 'Presentation'), ('INTERACTIVE', 'Interactive Content'), ('EBOOK', 'E-Book'), ('WORKSHEET', 'Worksheet'), ('QUIZ', 'Quiz')], max_length=20)),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public'), ('SCHOOL', 'School Only'), ('CLASSROOM', 'Classroom Only'), ('PRIVATE', 'Private')], default='SCHOOL', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='elibrary/resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'mp4', 'avi', 'mov', 'mp3', 'wav', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('external_url', models.URLField(blank=True, null=True)),
                ('embed_code', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_keywords', models.JSONField(blank=True, default=list)),
                ('ai_difficulty_score', models.FloatField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='library_resources', to='classroom.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_resources', to='users.school')),
            ],
            options={
                'db_table': 'learning_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elibrary.learningresource')),
            ],
            options={
                'db_table': 'collection_items',
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elibrary.readinglist')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elibrary.learningresource')),
            ],
            options={
                'db_table': 'reading_list_items',
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='readinglist',
            name='resources',
            field=models.ManyToManyField(related_name='reading_lists', through='elibrary.ReadingListItem', to='elibrary.learningresource'),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='📚', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='elibrary.resourcecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='users.school')),
            ],
            options={
                'verbose_name_plural': 'Resource categories',
                'db_table': 'resource_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='learningresource',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='resources', to='elibrary.resourcecategory'),
        ),
        migrations.CreateModel(
            name='ResourceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('FAVORITE', 'Favorite'), ('SHARE', 'Share'), ('COMPLETE', 'Complete')], max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='elibrary.learningresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_interactions',
            },
        ),
        migrations.CreateModel(
            name='ResourceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('not_helpful_votes', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='elibrary.learningresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('allow_collaboration', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_collections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('resources', models.ManyToManyField(related_name='collections', through='elibrary.CollectionItem', to='elibrary.learningresource')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_collections', to='users.school')),
            ],
            options={
                'db_table': 'study_collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elibrary.studycollection'),
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('recommendation_type', models.CharField(choices=[('SIMILAR', 'Similar Content'), ('PROGRESSION', 'Next in Progression'), ('TRENDING', 'Trending'), ('PERSONALIZED', 'Personalized')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='elibrary.learningresource')),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-confidence_score'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='ai_recommen_user_id_03ae61_idx'), models.Index(fields=['recommendation_type', 'confidence_score'], name='ai_recommen_recomme_cdac02_idx')],
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.AddIndex(
            model_name='readinglistitem',
            index=models.Index(fields=['reading_list', 'completed'], name='reading_lis_reading_2ed3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglistitem',
            index=models.Index(fields=['resource', 'completed'], name='reading_lis_resourc_4d9541_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readinglistitem',
            unique_together={('reading_list', 'resource')},
        ),
        migrations.AddIndex(
            model_name='readinglist',
            index=models.Index(fields=['user', 'created_at'], name='reading_lis_user_id_d007f3_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglist',
            index=models.Index(fields=['is_public', 'created_at'], name='reading_lis_is_publ_ea8540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcecategory',
            unique_together={('name', 'school')},
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['resource_type', 'is_published', 'is_approved'], name='learning_re_resourc_4ccc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['school', 'access_level'], name='learning_re_school__14de40_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['created_by', 'is_published'], name='learning_re_created_c00b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['is_featured', 'is_published'], name='learning_re_is_feat_10f26d_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceinteraction',
            index=models.Index(fields=['resource', 'user', 'interaction_type'], name='resource_in_resourc_ff9826_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceinteraction',
            index=models.Index(fields=['user', 'created_at'], name='resource_in_user_id_ef9dba_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceinteraction',
            index=models.Index(fields=['resource', 'interaction_type', 'created_at'], name='resource_in_resourc_e7c93d_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcereview',
            index=models.Index(fields=['resource', 'is_approved'], name='resource_re_resourc_16c1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcereview',
            index=models.Index(fields=['user', 'created_at'], name='resource_re_user_id_6dc06e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcereview',
            unique_together={('resource', 'user')},
        ),
        migrations.AddIndex(
            model_name='studycollection',
            index=models.Index(fields=['school', 'is_public'], name='study_colle_school__357528_idx'),
        ),
        migrations.AddIndex(
            model_name='studycollection',
            index=models.Index(fields=['created_by', 'created_at'], name='study_colle_created_3a07bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'resource')},
        ),
    ]
